# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import featureflow
from featureflow.api.project_api import ProjectApi  # noqa: E501
from featureflow.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_using_post5(self):
        """Test case for create_using_post5

        Create a new project  # noqa: E501
        """
        pass

    def test_delete_using_delete5(self):
        """Test case for delete_using_delete5

        Delete a project  # noqa: E501
        """
        pass

    def test_get_using_get5(self):
        """Test case for get_using_get5

        Get a project.  # noqa: E501
        """
        pass

    def test_list_using_get5(self):
        """Test case for list_using_get5

        Get all projects  # noqa: E501
        """
        pass

    def test_update_using_put5(self):
        """Test case for update_using_put5

        Update a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
