# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import featureflow
from featureflow.models.variant_split import VariantSplit  # noqa: E501
from featureflow.rest import ApiException


class TestVariantSplit(unittest.TestCase):
    """VariantSplit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariantSplit(self):
        """Test VariantSplit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = featureflow.models.variant_split.VariantSplit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
