# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import featureflow
from featureflow.api.feature_api import FeatureApi  # noqa: E501
from featureflow.rest import ApiException


class TestFeatureApi(unittest.TestCase):
    """FeatureApi unit test stubs"""

    def setUp(self):
        self.api = FeatureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_using_post4(self):
        """Test case for create_using_post4

        Create a new feature  # noqa: E501
        """
        pass

    def test_delete_using_delete4(self):
        """Test case for delete_using_delete4

        Delete a feature  # noqa: E501
        """
        pass

    def test_get_using_get4(self):
        """Test case for get_using_get4

        Get a feature.  # noqa: E501
        """
        pass

    def test_list_using_get4(self):
        """Test case for list_using_get4

        Get all features  # noqa: E501
        """
        pass

    def test_patch_feature_using_patch1(self):
        """Test case for patch_feature_using_patch1

        Merge patch a feature  # noqa: E501
        """
        pass

    def test_update_using_put4(self):
        """Test case for update_using_put4

        Update a feature  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
