# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import featureflow
from featureflow.api.environment_api import EnvironmentApi  # noqa: E501
from featureflow.rest import ApiException


class TestEnvironmentApi(unittest.TestCase):
    """EnvironmentApi unit test stubs"""

    def setUp(self):
        self.api = EnvironmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_using_post3(self):
        """Test case for create_using_post3

        Create a new environment  # noqa: E501
        """
        pass

    def test_delete_using_delete3(self):
        """Test case for delete_using_delete3

        Delete a environment  # noqa: E501
        """
        pass

    def test_get_using_get3(self):
        """Test case for get_using_get3

        Get an environment.  # noqa: E501
        """
        pass

    def test_list_using_get3(self):
        """Test case for list_using_get3

        Get all environments  # noqa: E501
        """
        pass

    def test_update_using_put3(self):
        """Test case for update_using_put3

        Update an environment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
