# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import featureflow
from featureflow.models.project_summary import ProjectSummary  # noqa: E501
from featureflow.rest import ApiException


class TestProjectSummary(unittest.TestCase):
    """ProjectSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectSummary(self):
        """Test ProjectSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = featureflow.models.project_summary.ProjectSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
