# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Condition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operator': 'str',
        'target': 'str',
        'values': 'list[object]'
    }

    attribute_map = {
        'operator': 'operator',
        'target': 'target',
        'values': 'values'
    }

    def __init__(self, operator=None, target=None, values=None):  # noqa: E501
        """Condition - a model defined in Swagger"""  # noqa: E501
        self._operator = None
        self._target = None
        self._values = None
        self.discriminator = None
        if operator is not None:
            self.operator = operator
        if target is not None:
            self.target = target
        if values is not None:
            self.values = values

    @property
    def operator(self):
        """Gets the operator of this Condition.  # noqa: E501


        :return: The operator of this Condition.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this Condition.


        :param operator: The operator of this Condition.  # noqa: E501
        :type: str
        """
        allowed_values = ["equals", "greaterThan", "lessThan", "greaterThanOrEqual", "lessThanOrEqual", "startsWith", "endsWith", "matches", "in", "notIn", "contains", "before", "after"]  # noqa: E501
        if operator not in allowed_values:
            raise ValueError(
                "Invalid value for `operator` ({0}), must be one of {1}"  # noqa: E501
                .format(operator, allowed_values)
            )

        self._operator = operator

    @property
    def target(self):
        """Gets the target of this Condition.  # noqa: E501


        :return: The target of this Condition.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Condition.


        :param target: The target of this Condition.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def values(self):
        """Gets the values of this Condition.  # noqa: E501


        :return: The values of this Condition.  # noqa: E501
        :rtype: list[object]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this Condition.


        :param values: The values of this Condition.  # noqa: E501
        :type: list[object]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Condition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Condition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
