# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Control(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'goals': 'list[str]',
        'off_variant_key': 'str',
        'rules': 'list[Rule]'
    }

    attribute_map = {
        'enabled': 'enabled',
        'goals': 'goals',
        'off_variant_key': 'offVariantKey',
        'rules': 'rules'
    }

    def __init__(self, enabled=None, goals=None, off_variant_key=None, rules=None):  # noqa: E501
        """Control - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._goals = None
        self._off_variant_key = None
        self._rules = None
        self.discriminator = None
        if enabled is not None:
            self.enabled = enabled
        if goals is not None:
            self.goals = goals
        if off_variant_key is not None:
            self.off_variant_key = off_variant_key
        if rules is not None:
            self.rules = rules

    @property
    def enabled(self):
        """Gets the enabled of this Control.  # noqa: E501


        :return: The enabled of this Control.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this Control.


        :param enabled: The enabled of this Control.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def goals(self):
        """Gets the goals of this Control.  # noqa: E501


        :return: The goals of this Control.  # noqa: E501
        :rtype: list[str]
        """
        return self._goals

    @goals.setter
    def goals(self, goals):
        """Sets the goals of this Control.


        :param goals: The goals of this Control.  # noqa: E501
        :type: list[str]
        """

        self._goals = goals

    @property
    def off_variant_key(self):
        """Gets the off_variant_key of this Control.  # noqa: E501


        :return: The off_variant_key of this Control.  # noqa: E501
        :rtype: str
        """
        return self._off_variant_key

    @off_variant_key.setter
    def off_variant_key(self, off_variant_key):
        """Sets the off_variant_key of this Control.


        :param off_variant_key: The off_variant_key of this Control.  # noqa: E501
        :type: str
        """

        self._off_variant_key = off_variant_key

    @property
    def rules(self):
        """Gets the rules of this Control.  # noqa: E501


        :return: The rules of this Control.  # noqa: E501
        :rtype: list[Rule]
        """
        return self._rules

    @rules.setter
    def rules(self, rules):
        """Sets the rules of this Control.


        :param rules: The rules of this Control.  # noqa: E501
        :type: list[Rule]
        """

        self._rules = rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Control, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Control):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
