# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EnvironmentUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'project_key': 'str',
        'production': 'bool',
        'name': 'str'
    }

    attribute_map = {
        'id': '_id',
        'project_key': 'projectKey',
        'production': 'production',
        'name': 'name'
    }

    def __init__(self, id=None, project_key=None, production=None, name=None):  # noqa: E501
        """EnvironmentUpdate - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._project_key = None
        self._production = None
        self._name = None
        self.discriminator = None
        self.id = id
        self.project_key = project_key
        self.production = production
        self.name = name

    @property
    def id(self):
        """Gets the id of this EnvironmentUpdate.  # noqa: E501

        Unique identifier  # noqa: E501

        :return: The id of this EnvironmentUpdate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EnvironmentUpdate.

        Unique identifier  # noqa: E501

        :param id: The id of this EnvironmentUpdate.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def project_key(self):
        """Gets the project_key of this EnvironmentUpdate.  # noqa: E501

        The unique project key that this environment is related to.  # noqa: E501

        :return: The project_key of this EnvironmentUpdate.  # noqa: E501
        :rtype: str
        """
        return self._project_key

    @project_key.setter
    def project_key(self, project_key):
        """Sets the project_key of this EnvironmentUpdate.

        The unique project key that this environment is related to.  # noqa: E501

        :param project_key: The project_key of this EnvironmentUpdate.  # noqa: E501
        :type: str
        """
        if project_key is None:
            raise ValueError("Invalid value for `project_key`, must not be `None`")  # noqa: E501

        self._project_key = project_key

    @property
    def production(self):
        """Gets the production of this EnvironmentUpdate.  # noqa: E501

        Whether the environment is considered a production environment.  # noqa: E501

        :return: The production of this EnvironmentUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._production

    @production.setter
    def production(self, production):
        """Sets the production of this EnvironmentUpdate.

        Whether the environment is considered a production environment.  # noqa: E501

        :param production: The production of this EnvironmentUpdate.  # noqa: E501
        :type: bool
        """
        if production is None:
            raise ValueError("Invalid value for `production`, must not be `None`")  # noqa: E501

        self._production = production

    @property
    def name(self):
        """Gets the name of this EnvironmentUpdate.  # noqa: E501

        The environment friendly name.  # noqa: E501

        :return: The name of this EnvironmentUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EnvironmentUpdate.

        The environment friendly name.  # noqa: E501

        :param name: The name of this EnvironmentUpdate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnvironmentUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnvironmentUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
