# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FeatureSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'environments': 'dict(str, Control)',
        'key': 'str',
        'links': 'list[Link]',
        'name': 'str',
        'project_key': 'str'
    }

    attribute_map = {
        'id': '_id',
        'environments': 'environments',
        'key': 'key',
        'links': 'links',
        'name': 'name',
        'project_key': 'projectKey'
    }

    def __init__(self, id=None, environments=None, key=None, links=None, name=None, project_key=None):  # noqa: E501
        """FeatureSummary - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._environments = None
        self._key = None
        self._links = None
        self._name = None
        self._project_key = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if environments is not None:
            self.environments = environments
        if key is not None:
            self.key = key
        if links is not None:
            self.links = links
        if name is not None:
            self.name = name
        if project_key is not None:
            self.project_key = project_key

    @property
    def id(self):
        """Gets the id of this FeatureSummary.  # noqa: E501


        :return: The id of this FeatureSummary.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FeatureSummary.


        :param id: The id of this FeatureSummary.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def environments(self):
        """Gets the environments of this FeatureSummary.  # noqa: E501


        :return: The environments of this FeatureSummary.  # noqa: E501
        :rtype: dict(str, Control)
        """
        return self._environments

    @environments.setter
    def environments(self, environments):
        """Sets the environments of this FeatureSummary.


        :param environments: The environments of this FeatureSummary.  # noqa: E501
        :type: dict(str, Control)
        """

        self._environments = environments

    @property
    def key(self):
        """Gets the key of this FeatureSummary.  # noqa: E501


        :return: The key of this FeatureSummary.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this FeatureSummary.


        :param key: The key of this FeatureSummary.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def links(self):
        """Gets the links of this FeatureSummary.  # noqa: E501


        :return: The links of this FeatureSummary.  # noqa: E501
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this FeatureSummary.


        :param links: The links of this FeatureSummary.  # noqa: E501
        :type: list[Link]
        """

        self._links = links

    @property
    def name(self):
        """Gets the name of this FeatureSummary.  # noqa: E501


        :return: The name of this FeatureSummary.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FeatureSummary.


        :param name: The name of this FeatureSummary.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def project_key(self):
        """Gets the project_key of this FeatureSummary.  # noqa: E501


        :return: The project_key of this FeatureSummary.  # noqa: E501
        :rtype: str
        """
        return self._project_key

    @project_key.setter
    def project_key(self, project_key):
        """Sets the project_key of this FeatureSummary.


        :param project_key: The project_key of this FeatureSummary.  # noqa: E501
        :type: str
        """

        self._project_key = project_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeatureSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeatureSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
