# coding: utf-8

"""
    Featureflow API

    Featureflow API documentation  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: contact@featureflow.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class VariantSplit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'split': 'int',
        'variant_key': 'str'
    }

    attribute_map = {
        'split': 'split',
        'variant_key': 'variantKey'
    }

    def __init__(self, split=None, variant_key=None):  # noqa: E501
        """VariantSplit - a model defined in Swagger"""  # noqa: E501
        self._split = None
        self._variant_key = None
        self.discriminator = None
        if split is not None:
            self.split = split
        if variant_key is not None:
            self.variant_key = variant_key

    @property
    def split(self):
        """Gets the split of this VariantSplit.  # noqa: E501


        :return: The split of this VariantSplit.  # noqa: E501
        :rtype: int
        """
        return self._split

    @split.setter
    def split(self, split):
        """Sets the split of this VariantSplit.


        :param split: The split of this VariantSplit.  # noqa: E501
        :type: int
        """

        self._split = split

    @property
    def variant_key(self):
        """Gets the variant_key of this VariantSplit.  # noqa: E501


        :return: The variant_key of this VariantSplit.  # noqa: E501
        :rtype: str
        """
        return self._variant_key

    @variant_key.setter
    def variant_key(self, variant_key):
        """Sets the variant_key of this VariantSplit.


        :param variant_key: The variant_key of this VariantSplit.  # noqa: E501
        :type: str
        """

        self._variant_key = variant_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VariantSplit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariantSplit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
